version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: "123456"
    volumes:
      - ./.pgdata/:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
